project_name: fake-gen
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - main: ./main.go
    id: "fake_gen"
    # binary: fake-gen
    targets:
     - "darwin_amd64"
     - "windows_amd64"
     - "linux_amd64"
  - env:
      - CGO_ENABLED=0
    # goos:
    #   - linux
    #   - windows
    #   - darwin
archives:
  - format: binary
  # - builds:
  #   - default
  # - replacements:
  #     darwin: Darwin
  #     linux: Linux
  #     windows: Windows
  #     allow_different_binary_count: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
