# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: fake-gen
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Run go mod vendor
    # Uses binaries in vendor folder instead of downloading new from internet
    flags:
      - -mod=vendor
# doesnot distribute prerelease versions
release:
  prerelease: auto
# Home Brew Tap
# universal_binaries:
#   - replace: true
# brews:
#   -
#     name: fake-gen
#     homepage: https://github.com/alidevhere/fake-gen
#     tap:
#       owner: https://github.com/alidevhere/fake-gen
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

